# Create volume snapshots

- name: Create volume snapshots
  os_volume_snapshot:
    state: present
    volume: '{{ item.vol_name}}'
    display_name: "{{ item.vol_name}}-{{ lookup('pipe', 'date +%Y-%m-%d-%H-%M-%S')}}"
    wait: yes
    timeout: 2000
    force: yes
    availability_zone: '{{ availability_zone}}'
  loop: '{{volumes}}'